version: '3'

services:
  web:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - DATABASE_URL=postgres://postgres:password@db/gpt3_turbo #tb updated
    depends_on:
      - cql-proxy # tb updated
  cql-proxy:
    image: datastax/cql-proxy:v0.1.4
    container_name: cql-proxy
    command: --astra-token <token> --astra-database-id <dbid> 
    ports:
      - "9042:9042"
    restart: on-failure